# Generated by Django 6.0.2 on 2026-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_admin_options_alter_staff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseusermodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='full name'),
        ),
    ]
