# Generated by Django 6.0.2 on 2026-02-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_baseusermodel_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseusermodel',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
