# Generated by Django 6.0.2 on 2026-02-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_stripe_payment_intent_order_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_session_id',
        ),
    ]
